/**
 * Assemble the runnable browser bundle at `lib/client.js`.
 *
 * The DSH web shell materializes a plugin's browser half through its vendored
 * cordis Loader, which expects one **plain-CJS factory** registered as
 * `window.__ModuleLoader__.load({ id, factory })` — exactly the shape
 * `dsh-client-ui-theme`'s own bundle has. That wrapper is what this script adds;
 * everything else is authored source.
 *
 * Why a build step at all, for a bundle that is not minified or transpiled:
 *
 *  1. The `--dsw-*` token catalog is *generated* from the installed DSH's
 *     stylesheets (`tools/extract-tokens.mjs`) so the token panel states real
 *     shipped values instead of guesses. Embedding it keeps the browser half to
 *     the single file the shell can serve — plugin bundles resolve their
 *     imports against a frozen module table, so a second served file is not an
 *     option.
 *  2. `src/client.js` (logic) and `src/panel.js` (React UI) must end up in ONE
 *     lexical scope: the components and the plugin body share `PLUGIN_ID`, the
 *     store, `commit`, and the picker engine. Concatenating them inside the
 *     factory is what gives them that shared scope without a module graph.
 *
 * The output is deliberately left readable and unmangled: it is the artifact a
 * user inspects when they want to know what this plugin actually injects.
 *
 * Run: node tools/build-client.mjs
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Read a project file relative to the plugin root. */
function read(relative) {
	const path = join(root, relative);
	if (!existsSync(path)) throw new Error(`missing source file: ${relative}`);
	return readFileSync(path, "utf8");
}

/** The placeholder in `src/client.js` that the generated catalog replaces. */
const TOKEN_PLACEHOLDER = "/* @__TOKEN_CATALOG__ */ { aliases: [] }";

/** The sentinel marking the declaration `src/panel.js` publishes for tests. */
const TEST_HANDLE_SENTINEL = "/* @__TEST_HANDLE__ */";

/**
 * Strip the module-level `export` keywords: inside the factory the source is one
 * function body, and the CJS `exports` object is what the Loader reads.
 */
function stripExports(source) {
	return source.replace(/^export const /gm, "const ").replace(/^export function /gm, "function ");
}

/**
 * Lift the test handle out of the factory body.
 *
 * The handle closes over the factory's own functions, so it cannot live outside
 * the factory — but leaving a diagnostic object on the plugin's public exports
 * is useful only to the tests. The declaration is removed from the assembled
 * body and re-emitted as part of the real `exports` object instead.
 *
 * A missing sentinel is a hard build failure: it is the only thing keeping the
 * test suite anchored to the shipped artifact rather than to a copy.
 */
function liftTestHandle(source) {
	const marker = `const testHandle = ${TEST_HANDLE_SENTINEL}`;
	const start = source.indexOf(marker);
	if (start < 0) {
		throw new Error(`src/panel.js no longer contains the test-handle sentinel ${TEST_HANDLE_SENTINEL}`);
	}
	// The declaration runs to the closing `};` on its own line.
	const end = source.indexOf("\n};", start);
	if (end < 0) throw new Error("the test handle is not terminated by a `};` line");
	const declaration = source.slice(start, end + 3);
	const remaining = `${source.slice(0, start)}${source.slice(end + 3)}`;
	return { remaining, declaration };
}

const catalog = JSON.parse(read("lib/tokens.json"));
const logic = stripExports(read("src/client.js"));
const { remaining: panel, declaration: handleDeclaration } = liftTestHandle(read("src/panel.js"));

if (!logic.includes(TOKEN_PLACEHOLDER)) {
	throw new Error(`src/client.js no longer contains the token placeholder ${TOKEN_PLACEHOLDER}`);
}
if (/^\s*export\s/m.test(logic) || /^\s*export\s/m.test(panel)) {
	throw new Error("an `export` statement survived stripping — the factory body must be plain script");
}

const body = logic.replace(TOKEN_PLACEHOLDER, JSON.stringify(catalog));

/** Line numbers in the emitted file must stay traceable to the sources. */
const header = `// ${"─".repeat(74)}
// dsh-custom-style — browser half (client plugin bundle).  GENERATED FILE.
//
// Assembled by tools/build-client.mjs from:
//   src/client.js   plugin body, state schema, CSS composition, picker engine
//   src/panel.js    React settings panel
//   lib/tokens.json generated --dsw-* catalog (tools/extract-tokens.mjs)
//
// Do not edit this file: edit the sources and re-run \`npm run build\`.
// The factory body is plain CJS whose \`require\` resolves against the shell's
// frozen module table, matching the shape the shipped ui-* bundles emit.
// ${"─".repeat(74)}

window.__ModuleLoader__.load({
\tid: ${JSON.stringify("dsh-custom-style")},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
`;

/**
 * Re-emit the lifted test handle as a real export.
 *
 * The declaration is `const testHandle = <sentinel> { ... };` — the initializer
 * is reused verbatim so the key list lives in exactly one place (the source).
 * The statement is collapsed onto one line so the footer's indentation is
 * uniform and needs no line-specific special-casing.
 */
function handleExport(declaration) {
	const open = declaration.indexOf("{");
	if (open < 0) throw new Error("the test handle has no object literal");
	const literal = declaration.slice(open, declaration.length - 1).trimEnd();
	if (!literal.endsWith("}")) throw new Error("the test handle object literal is malformed");
	return `exports.testHandle = ${literal.replace(/\s*\n\s*/g, " ")};`;
}

/** The factory body's own indentation depth, in tabs. */
const BODY_TABS = 2;

/**
 * Indent one block of source to sit inside the factory body.
 * Blank lines stay blank so the emitted file has no trailing whitespace.
 */
function indent(source, tabs = BODY_TABS) {
	const prefix = "\t".repeat(tabs);
	return source
		.split("\n")
		.map((line) => (line.trim() === "" ? "" : `${prefix}${line}`))
		.join("\n");
}

/**
 * The closing block: publish the surface, then return the module.
 *
 * Everything from here runs while the shell is still assembling the boot graph,
 * and a throw there is not a plugin failure — it is a "Failed to load plugins"
 * screen for the whole GUI. The exports are therefore assembled inside one
 * try/catch that still returns a usable (empty) module. Naming no injected
 * service in the fallback matters just as much: a fiber left PENDING by an
 * `inject` whose provider never appears fails the boot identically.
 */
function buildFooter() {
	const body = [
		"try {",
		"\texports.SETTINGS_NS = SETTINGS_NS;",
		"\texports.PRESETS = PRESETS;",
		"\texports.apply = apply;",
		"\texports.inject = inject;",
		`\t${handleExport(handleDeclaration)}`,
		"} catch (error) {",
		"\t// Never let surface assembly break the shell. The factory still",
		"\t// returns a module, so the loader sees this entry as active.",
		"\ttry {",
		"\t\tconsole.warn(`[${PLUGIN_ID}] could not publish the plugin surface:`, error && error.message);",
		"\t} catch {}",
		"\texports.apply = () => {};",
		"\texports.inject = [];",
		"}",
		"return module.exports;"
	].join("\n");
	return `\n${indent(body, BODY_TABS + 1)}\n\t}\n});\n`;
}

const footer = buildFooter();

const output = `${header}${indent(body)}\n${indent(panel)}\n${footer}`;

writeFileSync(join(root, "lib", "client.js"), output, "utf8");

const lines = output.split("\n").length;
process.stdout.write(`lib/client.js written: ${lines} lines, ${(output.length / 1024).toFixed(1)} KiB, ${catalog.aliases.length} tokens\n`);
